language:
    - python
python:
    - "2.7"
before_install:
    - "pip install python-coveralls"

# command to install dependencies
install:
    - "pip install -r requirements.txt"
    - "python setup.py develop"

# command to run tests
script:
    - nosetests --with-coverage --cover-erase --cover-package=sed_eval -v -w tests/

after_success:
    - coveralls
    - "python setup.py develop --uninstall"

after_failure:
    - "python setup.py develop --uninstall"